// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409170237_AddRecordingSourceCalendarEvent")]
    partial class AddRecordingSourceCalendarEvent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("backend.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int?>("SupporterId")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("SupporterId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("backend.Models.CalendarEvent", b =>
                {
                    b.Property<int>("CalendarEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("calendar_event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CalendarEventId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("RecurrenceRule")
                        .HasColumnType("text")
                        .HasColumnName("recurrence_rule");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("integer")
                        .HasColumnName("resident_id");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("safehouse_id");

                    b.Property<int?>("SourceTaskId")
                        .HasColumnType("integer")
                        .HasColumnName("source_task_id");

                    b.Property<string>("StaffUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("staff_user_id");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("CalendarEventId")
                        .HasName("calendar_events_pkey");

                    b.HasIndex("ResidentId");

                    b.HasIndex("SafehouseId")
                        .HasDatabaseName("calendar_events_safehouse_id_idx");

                    b.HasIndex("SourceTaskId");

                    b.HasIndex("StaffUserId")
                        .HasDatabaseName("calendar_events_staff_user_id_idx");

                    b.HasIndex("StaffUserId", "EventDate")
                        .HasDatabaseName("calendar_events_user_date_idx");

                    b.ToTable("calendar_events", (string)null);
                });

            modelBuilder.Entity("backend.Models.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("donation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DonationId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CampaignName")
                        .HasColumnType("text")
                        .HasColumnName("campaign_name");

                    b.Property<string>("ChannelSource")
                        .HasColumnType("text")
                        .HasColumnName("channel_source");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("text")
                        .HasColumnName("currency_code");

                    b.Property<DateOnly?>("DonationDate")
                        .HasColumnType("date")
                        .HasColumnName("donation_date");

                    b.Property<string>("DonationType")
                        .HasColumnType("text")
                        .HasColumnName("donation_type");

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("estimated_value");

                    b.Property<string>("ImpactUnit")
                        .HasColumnType("text")
                        .HasColumnName("impact_unit");

                    b.Property<bool?>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("ReferralPostId")
                        .HasColumnType("integer")
                        .HasColumnName("referral_post_id");

                    b.Property<int?>("SupporterId")
                        .HasColumnType("integer")
                        .HasColumnName("supporter_id");

                    b.HasKey("DonationId")
                        .HasName("donations_pkey");

                    b.HasIndex("CampaignName")
                        .HasDatabaseName("donations_campaign_name_idx");

                    b.HasIndex("SupporterId", "DonationType", "DonationDate")
                        .HasDatabaseName("donations_supporter_type_date_idx");

                    b.HasIndex(new[] { "ReferralPostId" }, "donations_referral_post_id_idx");

                    b.HasIndex(new[] { "SupporterId" }, "donations_supporter_id_idx");

                    b.ToTable("donations", (string)null);
                });

            modelBuilder.Entity("backend.Models.DonationAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("allocation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AllocationId"));

                    b.Property<DateOnly?>("AllocationDate")
                        .HasColumnType("date")
                        .HasColumnName("allocation_date");

                    b.Property<string>("AllocationNotes")
                        .HasColumnType("text")
                        .HasColumnName("allocation_notes");

                    b.Property<decimal?>("AmountAllocated")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_allocated");

                    b.Property<int>("DonationId")
                        .HasColumnType("integer")
                        .HasColumnName("donation_id");

                    b.Property<string>("ProgramArea")
                        .HasColumnType("text")
                        .HasColumnName("program_area");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("safehouse_id");

                    b.HasKey("AllocationId")
                        .HasName("donation_allocations_pkey");

                    b.HasIndex(new[] { "DonationId" }, "donation_allocations_donation_id_idx");

                    b.HasIndex(new[] { "SafehouseId" }, "donation_allocations_safehouse_id_idx");

                    b.ToTable("donation_allocations", (string)null);
                });

            modelBuilder.Entity("backend.Models.EducationRecord", b =>
                {
                    b.Property<int>("EducationRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("education_record_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EducationRecordId"));

                    b.Property<decimal?>("AttendanceRate")
                        .HasColumnType("numeric")
                        .HasColumnName("attendance_rate");

                    b.Property<string>("CompletionStatus")
                        .HasColumnType("text")
                        .HasColumnName("completion_status");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("text")
                        .HasColumnName("education_level");

                    b.Property<string>("EnrollmentStatus")
                        .HasColumnType("text")
                        .HasColumnName("enrollment_status");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("ProgressPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("progress_percent");

                    b.Property<DateOnly?>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("record_date");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer")
                        .HasColumnName("resident_id");

                    b.Property<string>("SchoolName")
                        .HasColumnType("text")
                        .HasColumnName("school_name");

                    b.HasKey("EducationRecordId")
                        .HasName("education_records_pkey");

                    b.HasIndex(new[] { "ResidentId" }, "education_records_resident_id_idx");

                    b.ToTable("education_records", (string)null);
                });

            modelBuilder.Entity("backend.Models.HealthWellbeingRecord", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("health_record_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HealthRecordId"));

                    b.Property<decimal?>("Bmi")
                        .HasColumnType("numeric")
                        .HasColumnName("bmi");

                    b.Property<bool?>("DentalCheckupDone")
                        .HasColumnType("boolean")
                        .HasColumnName("dental_checkup_done");

                    b.Property<decimal?>("EnergyLevelScore")
                        .HasColumnType("numeric")
                        .HasColumnName("energy_level_score");

                    b.Property<decimal?>("GeneralHealthScore")
                        .HasColumnType("numeric")
                        .HasColumnName("general_health_score");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("numeric")
                        .HasColumnName("height_cm");

                    b.Property<bool?>("MedicalCheckupDone")
                        .HasColumnType("boolean")
                        .HasColumnName("medical_checkup_done");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("NutritionScore")
                        .HasColumnType("numeric")
                        .HasColumnName("nutrition_score");

                    b.Property<bool?>("PsychologicalCheckupDone")
                        .HasColumnType("boolean")
                        .HasColumnName("psychological_checkup_done");

                    b.Property<DateOnly?>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("record_date");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer")
                        .HasColumnName("resident_id");

                    b.Property<decimal?>("SleepQualityScore")
                        .HasColumnType("numeric")
                        .HasColumnName("sleep_quality_score");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("weight_kg");

                    b.HasKey("HealthRecordId")
                        .HasName("health_wellbeing_records_pkey");

                    b.HasIndex(new[] { "ResidentId" }, "health_wellbeing_records_resident_id_idx");

                    b.ToTable("health_wellbeing_records", (string)null);
                });

            modelBuilder.Entity("backend.Models.HomeVisitation", b =>
                {
                    b.Property<int>("VisitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("visitation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VisitationId"));

                    b.Property<string>("FamilyCooperationLevel")
                        .HasColumnType("text")
                        .HasColumnName("family_cooperation_level");

                    b.Property<string>("FamilyMembersPresent")
                        .HasColumnType("text")
                        .HasColumnName("family_members_present");

                    b.Property<bool?>("FollowUpNeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("follow_up_needed");

                    b.Property<string>("FollowUpNotes")
                        .HasColumnType("text")
                        .HasColumnName("follow_up_notes");

                    b.Property<string>("LocationVisited")
                        .HasColumnType("text")
                        .HasColumnName("location_visited");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<string>("Purpose")
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer")
                        .HasColumnName("resident_id");

                    b.Property<bool?>("SafetyConcernsNoted")
                        .HasColumnType("boolean")
                        .HasColumnName("safety_concerns_noted");

                    b.Property<string>("SocialWorker")
                        .HasColumnType("text")
                        .HasColumnName("social_worker");

                    b.Property<DateOnly?>("VisitDate")
                        .HasColumnType("date")
                        .HasColumnName("visit_date");

                    b.Property<string>("VisitOutcome")
                        .HasColumnType("text")
                        .HasColumnName("visit_outcome");

                    b.Property<string>("VisitType")
                        .HasColumnType("text")
                        .HasColumnName("visit_type");

                    b.HasKey("VisitationId")
                        .HasName("home_visitations_pkey");

                    b.HasIndex(new[] { "ResidentId" }, "home_visitations_resident_id_idx");

                    b.ToTable("home_visitations", (string)null);
                });

            modelBuilder.Entity("backend.Models.InKindDonationItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<int>("DonationId")
                        .HasColumnType("integer")
                        .HasColumnName("donation_id");

                    b.Property<decimal?>("EstimatedUnitValue")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("estimated_unit_value");

                    b.Property<string>("IntendedUse")
                        .HasColumnType("text")
                        .HasColumnName("intended_use");

                    b.Property<string>("ItemCategory")
                        .HasColumnType("text")
                        .HasColumnName("item_category");

                    b.Property<string>("ItemName")
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("ReceivedCondition")
                        .HasColumnType("text")
                        .HasColumnName("received_condition");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("text")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("ItemId")
                        .HasName("in_kind_donation_items_pkey");

                    b.HasIndex(new[] { "DonationId" }, "in_kind_donation_items_donation_id_idx");

                    b.ToTable("in_kind_donation_items", (string)null);
                });

            modelBuilder.Entity("backend.Models.IncidentReport", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("incident_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncidentId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("FollowUpRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("follow_up_required");

                    b.Property<DateOnly?>("IncidentDate")
                        .HasColumnType("date")
                        .HasColumnName("incident_date");

                    b.Property<string>("IncidentType")
                        .HasColumnType("text")
                        .HasColumnName("incident_type");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("text")
                        .HasColumnName("reported_by");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("integer")
                        .HasColumnName("resident_id");

                    b.Property<DateOnly?>("ResolutionDate")
                        .HasColumnType("date")
                        .HasColumnName("resolution_date");

                    b.Property<bool?>("Resolved")
                        .HasColumnType("boolean")
                        .HasColumnName("resolved");

                    b.Property<string>("ResponseTaken")
                        .HasColumnType("text")
                        .HasColumnName("response_taken");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Severity")
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.HasKey("IncidentId")
                        .HasName("incident_reports_pkey");

                    b.HasIndex(new[] { "ResidentId" }, "incident_reports_resident_id_idx");

                    b.HasIndex(new[] { "SafehouseId" }, "incident_reports_safehouse_id_idx");

                    b.ToTable("incident_reports", (string)null);
                });

            modelBuilder.Entity("backend.Models.InterventionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("plan_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanId"));

                    b.Property<DateOnly?>("CaseConferenceDate")
                        .HasColumnType("date")
                        .HasColumnName("case_conference_date");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PlanCategory")
                        .HasColumnType("text")
                        .HasColumnName("plan_category");

                    b.Property<string>("PlanDescription")
                        .HasColumnType("text")
                        .HasColumnName("plan_description");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer")
                        .HasColumnName("resident_id");

                    b.Property<string>("ServicesProvided")
                        .HasColumnType("text")
                        .HasColumnName("services_provided");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.Property<decimal?>("TargetValue")
                        .HasColumnType("numeric")
                        .HasColumnName("target_value");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PlanId")
                        .HasName("intervention_plans_pkey");

                    b.HasIndex(new[] { "ResidentId" }, "intervention_plans_resident_id_idx");

                    b.ToTable("intervention_plans", (string)null);
                });

            modelBuilder.Entity("backend.Models.MlPrediction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_name");

                    b.Property<string>("ModelVersion")
                        .HasColumnType("text")
                        .HasColumnName("model_version");

                    b.Property<DateTime>("PredictedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("predicted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("score");

                    b.Property<string>("ScoreLabel")
                        .HasColumnType("text")
                        .HasColumnName("score_label");

                    b.HasKey("Id")
                        .HasName("ml_predictions_pkey");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("idx_ml_predictions_entity");

                    b.HasIndex("ModelName", "Score")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_ml_predictions_model_score");

                    b.HasIndex("ModelName", "ScoreLabel")
                        .HasDatabaseName("idx_ml_predictions_label");

                    b.HasIndex("EntityType", "EntityId", "ModelName")
                        .IsUnique()
                        .HasDatabaseName("ml_predictions_entity_type_entity_id_model_name_key");

                    b.ToTable("ml_predictions", (string)null);
                });

            modelBuilder.Entity("backend.Models.MlPredictionHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_name");

                    b.Property<string>("ModelVersion")
                        .HasColumnType("text")
                        .HasColumnName("model_version");

                    b.Property<DateTime>("PredictedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("predicted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("score");

                    b.Property<string>("ScoreLabel")
                        .HasColumnType("text")
                        .HasColumnName("score_label");

                    b.HasKey("Id")
                        .HasName("ml_prediction_history_pkey");

                    b.HasIndex("ModelName", "PredictedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_ml_history_model");

                    b.HasIndex("EntityType", "EntityId", "ModelName", "PredictedAt")
                        .IsDescending(false, false, false, true)
                        .HasDatabaseName("idx_ml_history_entity_model");

                    b.ToTable("ml_prediction_history", (string)null);
                });

            modelBuilder.Entity("backend.Models.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("partner_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartnerId"));

                    b.Property<string>("ContactName")
                        .HasColumnType("text")
                        .HasColumnName("contact_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PartnerName")
                        .HasColumnType("text")
                        .HasColumnName("partner_name");

                    b.Property<string>("PartnerType")
                        .HasColumnType("text")
                        .HasColumnName("partner_type");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("RoleType")
                        .HasColumnType("text")
                        .HasColumnName("role_type");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("PartnerId")
                        .HasName("partners_pkey");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("backend.Models.PartnerAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateOnly?>("AssignmentEnd")
                        .HasColumnType("date")
                        .HasColumnName("assignment_end");

                    b.Property<DateOnly?>("AssignmentStart")
                        .HasColumnType("date")
                        .HasColumnName("assignment_start");

                    b.Property<bool?>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<int>("PartnerId")
                        .HasColumnType("integer")
                        .HasColumnName("partner_id");

                    b.Property<string>("ProgramArea")
                        .HasColumnType("text")
                        .HasColumnName("program_area");

                    b.Property<string>("ResponsibilityNotes")
                        .HasColumnType("text")
                        .HasColumnName("responsibility_notes");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("AssignmentId")
                        .HasName("partner_assignments_pkey");

                    b.HasIndex(new[] { "PartnerId" }, "partner_assignments_partner_id_idx");

                    b.HasIndex(new[] { "SafehouseId" }, "partner_assignments_safehouse_id_idx");

                    b.ToTable("partner_assignments", (string)null);
                });

            modelBuilder.Entity("backend.Models.ProcessRecording", b =>
                {
                    b.Property<int>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recording_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecordingId"));

                    b.Property<bool?>("ConcernsFlagged")
                        .HasColumnType("boolean")
                        .HasColumnName("concerns_flagged");

                    b.Property<string>("EmotionalStateEnd")
                        .HasColumnType("text")
                        .HasColumnName("emotional_state_end");

                    b.Property<string>("EmotionalStateObserved")
                        .HasColumnType("text")
                        .HasColumnName("emotional_state_observed");

                    b.Property<string>("FollowUpActions")
                        .HasColumnType("text")
                        .HasColumnName("follow_up_actions");

                    b.Property<string>("InterventionsApplied")
                        .HasColumnType("text")
                        .HasColumnName("interventions_applied");

                    b.Property<bool?>("NeedsCaseConference")
                        .HasColumnType("boolean");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("text")
                        .HasColumnName("notes_restricted");

                    b.Property<bool?>("ProgressNoted")
                        .HasColumnType("boolean")
                        .HasColumnName("progress_noted");

                    b.Property<bool?>("ReadyForReintegration")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ReferralMade")
                        .HasColumnType("boolean")
                        .HasColumnName("referral_made");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer")
                        .HasColumnName("resident_id");

                    b.Property<DateOnly?>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<int?>("SessionDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("session_duration_minutes");

                    b.Property<string>("SessionNarrative")
                        .HasColumnType("text")
                        .HasColumnName("session_narrative");

                    b.Property<string>("SessionType")
                        .HasColumnType("text")
                        .HasColumnName("session_type");

                    b.Property<string>("SocialWorker")
                        .HasColumnType("text")
                        .HasColumnName("social_worker");

                    b.Property<int?>("SourceCalendarEventId")
                        .HasColumnType("integer");

                    b.HasKey("RecordingId")
                        .HasName("process_recordings_pkey");

                    b.HasIndex("SourceCalendarEventId");

                    b.HasIndex(new[] { "ResidentId" }, "process_recordings_resident_id_idx");

                    b.ToTable("process_recordings", (string)null);
                });

            modelBuilder.Entity("backend.Models.PublicImpactSnapshot", b =>
                {
                    b.Property<int>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SnapshotId"));

                    b.Property<string>("Headline")
                        .HasColumnType("text")
                        .HasColumnName("headline");

                    b.Property<bool?>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("MetricPayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("metric_payload_json");

                    b.Property<DateOnly?>("PublishedAt")
                        .HasColumnType("date")
                        .HasColumnName("published_at");

                    b.Property<DateOnly?>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.Property<string>("SummaryText")
                        .HasColumnType("text")
                        .HasColumnName("summary_text");

                    b.HasKey("SnapshotId")
                        .HasName("public_impact_snapshots_pkey");

                    b.ToTable("public_impact_snapshots", (string)null);
                });

            modelBuilder.Entity("backend.Models.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("resident_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResidentId"));

                    b.Property<string>("AgeUponAdmission")
                        .HasColumnType("text")
                        .HasColumnName("age_upon_admission");

                    b.Property<string>("AssignedSocialWorker")
                        .HasColumnType("text")
                        .HasColumnName("assigned_social_worker");

                    b.Property<string>("BirthStatus")
                        .HasColumnType("text")
                        .HasColumnName("birth_status");

                    b.Property<string>("CaseCategory")
                        .HasColumnType("text")
                        .HasColumnName("case_category");

                    b.Property<string>("CaseControlNo")
                        .HasColumnType("text")
                        .HasColumnName("case_control_no");

                    b.Property<string>("CaseStatus")
                        .HasColumnType("text")
                        .HasColumnName("case_status");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentRiskLevel")
                        .HasColumnType("text")
                        .HasColumnName("current_risk_level");

                    b.Property<DateOnly?>("DateCaseStudyPrepared")
                        .HasColumnType("date")
                        .HasColumnName("date_case_study_prepared");

                    b.Property<DateOnly?>("DateClosed")
                        .HasColumnType("date")
                        .HasColumnName("date_closed");

                    b.Property<DateOnly?>("DateColbObtained")
                        .HasColumnType("date")
                        .HasColumnName("date_colb_obtained");

                    b.Property<DateOnly?>("DateColbRegistered")
                        .HasColumnType("date")
                        .HasColumnName("date_colb_registered");

                    b.Property<DateOnly?>("DateEnrolled")
                        .HasColumnType("date")
                        .HasColumnName("date_enrolled");

                    b.Property<DateOnly?>("DateOfAdmission")
                        .HasColumnType("date")
                        .HasColumnName("date_of_admission");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<bool?>("FamilyIndigenous")
                        .HasColumnType("boolean")
                        .HasColumnName("family_indigenous");

                    b.Property<bool?>("FamilyInformalSettler")
                        .HasColumnType("boolean")
                        .HasColumnName("family_informal_settler");

                    b.Property<bool?>("FamilyIs4ps")
                        .HasColumnType("boolean")
                        .HasColumnName("family_is_4ps");

                    b.Property<bool?>("FamilyParentPwd")
                        .HasColumnType("boolean")
                        .HasColumnName("family_parent_pwd");

                    b.Property<bool?>("FamilySoloParent")
                        .HasColumnType("boolean")
                        .HasColumnName("family_solo_parent");

                    b.Property<bool?>("HasSpecialNeeds")
                        .HasColumnType("boolean")
                        .HasColumnName("has_special_needs");

                    b.Property<string>("InitialCaseAssessment")
                        .HasColumnType("text")
                        .HasColumnName("initial_case_assessment");

                    b.Property<string>("InitialRiskLevel")
                        .HasColumnType("text")
                        .HasColumnName("initial_risk_level");

                    b.Property<string>("InternalCode")
                        .HasColumnType("text")
                        .HasColumnName("internal_code");

                    b.Property<bool?>("IsPwd")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pwd");

                    b.Property<string>("LengthOfStay")
                        .HasColumnType("text")
                        .HasColumnName("length_of_stay");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("text")
                        .HasColumnName("notes_restricted");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("text")
                        .HasColumnName("place_of_birth");

                    b.Property<string>("PresentAge")
                        .HasColumnType("text")
                        .HasColumnName("present_age");

                    b.Property<string>("PwdType")
                        .HasColumnType("text")
                        .HasColumnName("pwd_type");

                    b.Property<string>("ReferralSource")
                        .HasColumnType("text")
                        .HasColumnName("referral_source");

                    b.Property<string>("ReferringAgencyPerson")
                        .HasColumnType("text")
                        .HasColumnName("referring_agency_person");

                    b.Property<string>("ReintegrationStatus")
                        .HasColumnType("text")
                        .HasColumnName("reintegration_status");

                    b.Property<string>("ReintegrationType")
                        .HasColumnType("text")
                        .HasColumnName("reintegration_type");

                    b.Property<string>("Religion")
                        .HasColumnType("text")
                        .HasColumnName("religion");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Sex")
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.Property<string>("SpecialNeedsDiagnosis")
                        .HasColumnType("text")
                        .HasColumnName("special_needs_diagnosis");

                    b.Property<bool?>("SubCatAtRisk")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_at_risk");

                    b.Property<bool?>("SubCatChildLabor")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_child_labor");

                    b.Property<bool?>("SubCatChildWithHiv")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_child_with_hiv");

                    b.Property<bool?>("SubCatCicl")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_cicl");

                    b.Property<bool?>("SubCatOrphaned")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_orphaned");

                    b.Property<bool?>("SubCatOsaec")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_osaec");

                    b.Property<bool?>("SubCatPhysicalAbuse")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_physical_abuse");

                    b.Property<bool?>("SubCatSexualAbuse")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_sexual_abuse");

                    b.Property<bool?>("SubCatStreetChild")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_street_child");

                    b.Property<bool?>("SubCatTrafficked")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_trafficked");

                    b.HasKey("ResidentId")
                        .HasName("residents_pkey");

                    b.HasIndex(new[] { "SafehouseId" }, "residents_safehouse_id_idx");

                    b.ToTable("residents", (string)null);
                });

            modelBuilder.Entity("backend.Models.Safehouse", b =>
                {
                    b.Property<int>("SafehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("safehouse_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SafehouseId"));

                    b.Property<int?>("CapacityGirls")
                        .HasColumnType("integer")
                        .HasColumnName("capacity_girls");

                    b.Property<int?>("CapacityStaff")
                        .HasColumnType("integer")
                        .HasColumnName("capacity_staff");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<int?>("CurrentOccupancy")
                        .HasColumnType("integer")
                        .HasColumnName("current_occupancy");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("OpenDate")
                        .HasColumnType("date")
                        .HasColumnName("open_date");

                    b.Property<string>("Province")
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("SafehouseCode")
                        .HasColumnType("text")
                        .HasColumnName("safehouse_code");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("SafehouseId")
                        .HasName("safehouses_pkey");

                    b.ToTable("safehouses", (string)null);
                });

            modelBuilder.Entity("backend.Models.SafehouseMonthlyMetric", b =>
                {
                    b.Property<int>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("metric_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MetricId"));

                    b.Property<int?>("ActiveResidents")
                        .HasColumnType("integer")
                        .HasColumnName("active_residents");

                    b.Property<decimal?>("AvgEducationProgress")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_education_progress");

                    b.Property<decimal?>("AvgHealthScore")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_health_score");

                    b.Property<int?>("HomeVisitationCount")
                        .HasColumnType("integer")
                        .HasColumnName("home_visitation_count");

                    b.Property<int?>("IncidentCount")
                        .HasColumnType("integer")
                        .HasColumnName("incident_count");

                    b.Property<DateOnly?>("MonthEnd")
                        .HasColumnType("date")
                        .HasColumnName("month_end");

                    b.Property<DateOnly?>("MonthStart")
                        .HasColumnType("date")
                        .HasColumnName("month_start");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("ProcessRecordingCount")
                        .HasColumnType("integer")
                        .HasColumnName("process_recording_count");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("safehouse_id");

                    b.HasKey("MetricId")
                        .HasName("safehouse_monthly_metrics_pkey");

                    b.HasIndex(new[] { "SafehouseId" }, "safehouse_monthly_metrics_safehouse_id_idx");

                    b.ToTable("safehouse_monthly_metrics", (string)null);
                });

            modelBuilder.Entity("backend.Models.SocialMediaPost", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<int?>("AvgViewDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("avg_view_duration_seconds");

                    b.Property<decimal?>("BoostBudgetPhp")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("boost_budget_php");

                    b.Property<string>("CallToActionType")
                        .HasColumnType("text")
                        .HasColumnName("call_to_action_type");

                    b.Property<string>("CampaignName")
                        .HasColumnType("text")
                        .HasColumnName("campaign_name");

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<int?>("CaptionLength")
                        .HasColumnType("integer")
                        .HasColumnName("caption_length");

                    b.Property<int?>("ClickThroughs")
                        .HasColumnType("integer")
                        .HasColumnName("click_throughs");

                    b.Property<int?>("Comments")
                        .HasColumnType("integer")
                        .HasColumnName("comments");

                    b.Property<string>("ContentTopic")
                        .HasColumnType("text")
                        .HasColumnName("content_topic");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("text")
                        .HasColumnName("day_of_week");

                    b.Property<int?>("DonationReferrals")
                        .HasColumnType("integer")
                        .HasColumnName("donation_referrals");

                    b.Property<decimal?>("EngagementRate")
                        .HasColumnType("numeric")
                        .HasColumnName("engagement_rate");

                    b.Property<decimal?>("EstimatedDonationValuePhp")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("estimated_donation_value_php");

                    b.Property<bool?>("FeaturesResidentStory")
                        .HasColumnType("boolean")
                        .HasColumnName("features_resident_story");

                    b.Property<int?>("FollowerCountAtPost")
                        .HasColumnType("integer")
                        .HasColumnName("follower_count_at_post");

                    b.Property<int?>("Forwards")
                        .HasColumnType("integer")
                        .HasColumnName("forwards");

                    b.Property<bool?>("HasCallToAction")
                        .HasColumnType("boolean")
                        .HasColumnName("has_call_to_action");

                    b.Property<string>("Hashtags")
                        .HasColumnType("text")
                        .HasColumnName("hashtags");

                    b.Property<int?>("Impressions")
                        .HasColumnType("integer")
                        .HasColumnName("impressions");

                    b.Property<bool?>("IsBoosted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_boosted");

                    b.Property<int?>("Likes")
                        .HasColumnType("integer")
                        .HasColumnName("likes");

                    b.Property<string>("MediaType")
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<int?>("MentionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("mentions_count");

                    b.Property<int?>("NumHashtags")
                        .HasColumnType("integer")
                        .HasColumnName("num_hashtags");

                    b.Property<string>("Platform")
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("PlatformPostId")
                        .HasColumnType("text")
                        .HasColumnName("platform_post_id");

                    b.Property<int?>("PostHour")
                        .HasColumnType("integer")
                        .HasColumnName("post_hour");

                    b.Property<string>("PostType")
                        .HasColumnType("text")
                        .HasColumnName("post_type");

                    b.Property<string>("PostUrl")
                        .HasColumnType("text")
                        .HasColumnName("post_url");

                    b.Property<int?>("ProfileVisits")
                        .HasColumnType("integer")
                        .HasColumnName("profile_visits");

                    b.Property<int?>("Reach")
                        .HasColumnType("integer")
                        .HasColumnName("reach");

                    b.Property<int?>("Saves")
                        .HasColumnType("integer")
                        .HasColumnName("saves");

                    b.Property<string>("SentimentTone")
                        .HasColumnType("text")
                        .HasColumnName("sentiment_tone");

                    b.Property<int?>("Shares")
                        .HasColumnType("integer")
                        .HasColumnName("shares");

                    b.Property<int?>("SubscriberCountAtPost")
                        .HasColumnType("integer")
                        .HasColumnName("subscriber_count_at_post");

                    b.Property<int?>("VideoViews")
                        .HasColumnType("integer")
                        .HasColumnName("video_views");

                    b.Property<int?>("WatchTimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("watch_time_seconds");

                    b.HasKey("PostId")
                        .HasName("social_media_posts_pkey");

                    b.HasIndex("CampaignName", "CreatedAt")
                        .HasDatabaseName("social_posts_campaign_created_idx");

                    b.ToTable("social_media_posts", (string)null);
                });

            modelBuilder.Entity("backend.Models.StaffTask", b =>
                {
                    b.Property<int>("StaffTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("staff_task_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StaffTaskId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ContextJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("context_json");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueTriggerDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_trigger_date");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("integer")
                        .HasColumnName("resident_id");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("safehouse_id");

                    b.Property<DateTime?>("SnoozeUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snooze_until");

                    b.Property<int?>("SourceEntityId")
                        .HasColumnType("integer")
                        .HasColumnName("source_entity_id");

                    b.Property<string>("SourceEntityType")
                        .HasColumnType("text")
                        .HasColumnName("source_entity_type");

                    b.Property<string>("StaffUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("staff_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("task_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("StaffTaskId")
                        .HasName("staff_tasks_pkey");

                    b.HasIndex("ResidentId");

                    b.HasIndex("SafehouseId")
                        .HasDatabaseName("staff_tasks_safehouse_id_idx");

                    b.HasIndex("StaffUserId")
                        .HasDatabaseName("staff_tasks_staff_user_id_idx");

                    b.HasIndex("StaffUserId", "Status")
                        .HasDatabaseName("staff_tasks_user_status_idx");

                    b.ToTable("staff_tasks", (string)null);
                });

            modelBuilder.Entity("backend.Models.Supporter", b =>
                {
                    b.Property<int>("SupporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("supporter_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupporterId"));

                    b.Property<string>("AcquisitionChannel")
                        .HasColumnType("text")
                        .HasColumnName("acquisition_channel");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("FirstDonationDate")
                        .HasColumnType("date")
                        .HasColumnName("first_donation_date");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("text")
                        .HasColumnName("organization_name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("text")
                        .HasColumnName("relationship_type");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SupporterType")
                        .HasColumnType("text")
                        .HasColumnName("supporter_type");

                    b.HasKey("SupporterId")
                        .HasName("supporters_pkey");

                    b.ToTable("supporters", (string)null);
                });

            modelBuilder.Entity("backend.Models.UserSafehouse", b =>
                {
                    b.Property<int>("UserSafehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_safehouse_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserSafehouseId"));

                    b.Property<int>("SafehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("UserSafehouseId")
                        .HasName("user_safehouses_pkey");

                    b.HasIndex("SafehouseId");

                    b.HasIndex("UserId", "SafehouseId")
                        .IsUnique()
                        .HasDatabaseName("user_safehouses_user_safehouse_idx");

                    b.ToTable("user_safehouses", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.ApplicationUser", b =>
                {
                    b.HasOne("backend.Models.Supporter", "Supporter")
                        .WithMany()
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Supporter");
                });

            modelBuilder.Entity("backend.Models.CalendarEvent", b =>
                {
                    b.HasOne("backend.Models.Resident", "Resident")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("calendar_events_resident_id_fkey");

                    b.HasOne("backend.Models.Safehouse", "Safehouse")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("calendar_events_safehouse_id_fkey");

                    b.HasOne("backend.Models.StaffTask", "SourceTask")
                        .WithMany()
                        .HasForeignKey("SourceTaskId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("calendar_events_source_task_id_fkey");

                    b.HasOne("backend.Models.ApplicationUser", "StaffUser")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("calendar_events_staff_user_id_fkey");

                    b.Navigation("Resident");

                    b.Navigation("Safehouse");

                    b.Navigation("SourceTask");

                    b.Navigation("StaffUser");
                });

            modelBuilder.Entity("backend.Models.Donation", b =>
                {
                    b.HasOne("backend.Models.SocialMediaPost", "ReferralPost")
                        .WithMany("Donations")
                        .HasForeignKey("ReferralPostId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("donations_referral_post_id_fkey");

                    b.HasOne("backend.Models.Supporter", "Supporter")
                        .WithMany("Donations")
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("donations_supporter_id_fkey");

                    b.Navigation("ReferralPost");

                    b.Navigation("Supporter");
                });

            modelBuilder.Entity("backend.Models.DonationAllocation", b =>
                {
                    b.HasOne("backend.Models.Donation", "Donation")
                        .WithMany("DonationAllocations")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("donation_allocations_donation_id_fkey");

                    b.HasOne("backend.Models.Safehouse", "Safehouse")
                        .WithMany("DonationAllocations")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("donation_allocations_safehouse_id_fkey");

                    b.Navigation("Donation");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("backend.Models.EducationRecord", b =>
                {
                    b.HasOne("backend.Models.Resident", "Resident")
                        .WithMany("EducationRecords")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("education_records_resident_id_fkey");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("backend.Models.HealthWellbeingRecord", b =>
                {
                    b.HasOne("backend.Models.Resident", "Resident")
                        .WithMany("HealthWellbeingRecords")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("health_wellbeing_records_resident_id_fkey");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("backend.Models.HomeVisitation", b =>
                {
                    b.HasOne("backend.Models.Resident", "Resident")
                        .WithMany("HomeVisitations")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("home_visitations_resident_id_fkey");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("backend.Models.InKindDonationItem", b =>
                {
                    b.HasOne("backend.Models.Donation", "Donation")
                        .WithMany("InKindDonationItems")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("in_kind_donation_items_donation_id_fkey");

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("backend.Models.IncidentReport", b =>
                {
                    b.HasOne("backend.Models.Resident", "Resident")
                        .WithMany("IncidentReports")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("incident_reports_resident_id_fkey");

                    b.HasOne("backend.Models.Safehouse", "Safehouse")
                        .WithMany("IncidentReports")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("incident_reports_safehouse_id_fkey");

                    b.Navigation("Resident");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("backend.Models.InterventionPlan", b =>
                {
                    b.HasOne("backend.Models.Resident", "Resident")
                        .WithMany("InterventionPlans")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("intervention_plans_resident_id_fkey");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("backend.Models.PartnerAssignment", b =>
                {
                    b.HasOne("backend.Models.Partner", "Partner")
                        .WithMany("PartnerAssignments")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("partner_assignments_partner_id_fkey");

                    b.HasOne("backend.Models.Safehouse", "Safehouse")
                        .WithMany("PartnerAssignments")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("partner_assignments_safehouse_id_fkey");

                    b.Navigation("Partner");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("backend.Models.ProcessRecording", b =>
                {
                    b.HasOne("backend.Models.Resident", "Resident")
                        .WithMany("ProcessRecordings")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("process_recordings_resident_id_fkey");

                    b.HasOne("backend.Models.CalendarEvent", "SourceCalendarEvent")
                        .WithMany()
                        .HasForeignKey("SourceCalendarEventId");

                    b.Navigation("Resident");

                    b.Navigation("SourceCalendarEvent");
                });

            modelBuilder.Entity("backend.Models.Resident", b =>
                {
                    b.HasOne("backend.Models.Safehouse", "Safehouse")
                        .WithMany("Residents")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("residents_safehouse_id_fkey");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("backend.Models.SafehouseMonthlyMetric", b =>
                {
                    b.HasOne("backend.Models.Safehouse", "Safehouse")
                        .WithMany("SafehouseMonthlyMetrics")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("safehouse_monthly_metrics_safehouse_id_fkey");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("backend.Models.StaffTask", b =>
                {
                    b.HasOne("backend.Models.Resident", "Resident")
                        .WithMany("StaffTasks")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("staff_tasks_resident_id_fkey");

                    b.HasOne("backend.Models.Safehouse", "Safehouse")
                        .WithMany("StaffTasks")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("staff_tasks_safehouse_id_fkey");

                    b.HasOne("backend.Models.ApplicationUser", "StaffUser")
                        .WithMany("StaffTasks")
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("staff_tasks_staff_user_id_fkey");

                    b.Navigation("Resident");

                    b.Navigation("Safehouse");

                    b.Navigation("StaffUser");
                });

            modelBuilder.Entity("backend.Models.UserSafehouse", b =>
                {
                    b.HasOne("backend.Models.Safehouse", "Safehouse")
                        .WithMany("UserSafehouses")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_safehouses_safehouse_id_fkey");

                    b.HasOne("backend.Models.ApplicationUser", "User")
                        .WithMany("UserSafehouses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_safehouses_user_id_fkey");

                    b.Navigation("Safehouse");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.ApplicationUser", b =>
                {
                    b.Navigation("CalendarEvents");

                    b.Navigation("StaffTasks");

                    b.Navigation("UserSafehouses");
                });

            modelBuilder.Entity("backend.Models.Donation", b =>
                {
                    b.Navigation("DonationAllocations");

                    b.Navigation("InKindDonationItems");
                });

            modelBuilder.Entity("backend.Models.Partner", b =>
                {
                    b.Navigation("PartnerAssignments");
                });

            modelBuilder.Entity("backend.Models.Resident", b =>
                {
                    b.Navigation("CalendarEvents");

                    b.Navigation("EducationRecords");

                    b.Navigation("HealthWellbeingRecords");

                    b.Navigation("HomeVisitations");

                    b.Navigation("IncidentReports");

                    b.Navigation("InterventionPlans");

                    b.Navigation("ProcessRecordings");

                    b.Navigation("StaffTasks");
                });

            modelBuilder.Entity("backend.Models.Safehouse", b =>
                {
                    b.Navigation("CalendarEvents");

                    b.Navigation("DonationAllocations");

                    b.Navigation("IncidentReports");

                    b.Navigation("PartnerAssignments");

                    b.Navigation("Residents");

                    b.Navigation("SafehouseMonthlyMetrics");

                    b.Navigation("StaffTasks");

                    b.Navigation("UserSafehouses");
                });

            modelBuilder.Entity("backend.Models.SocialMediaPost", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("backend.Models.Supporter", b =>
                {
                    b.Navigation("Donations");
                });
#pragma warning restore 612, 618
        }
    }
}
